version: '3.4'

services:
  my_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_mysql_db
    ports:
      - '3300:3300'
    volumes:
      - my_volume:/var/lib/mysql

  dockerexpress:
    image: dockerexpress
    build:
      context: dockerExpress
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on: 
      - my_mysql

volumes: 
  my_volume:
